=== WellsYuu/corresponding-auxiliary-data/系列2-缓存中间件集群优化/7.第七部分笔记/openresty-1.13.6.1/bundle/nginx-1.13.6/docs/dtd/change_log_conf.dtd
<!--
  - Copyright 2022 the original author or authors.
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  -     http://www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
  -->

<!ELEMENT configuration   (length, start, indent, changes+) >

<!ELEMENT length          (#PCDATA) >
<!ELEMENT start           (#PCDATA) >
<!ELEMENT indent          (#PCDATA) >

<!ELEMENT changes         (title, length,
                           bugfix, feature, change, workaround,
                           (month, month, month, month, month, month,
                            month, month, month, month, month, month)?) >

<!ATTLIST changes         lang ( ru | en) #REQUIRED>

<!ELEMENT title           (#PCDATA) >

<!ELEMENT bugfix          (#PCDATA) >
<!ELEMENT feature         (#PCDATA) >
<!ELEMENT change          (#PCDATA) >
<!ELEMENT workaround      (#PCDATA) >

<!ELEMENT month           (#PCDATA) >

=== WellsYuu/corresponding-auxiliary-data/系列2-缓存中间件集群优化/7.第七部分笔记/openresty-1.13.6.1/bundle/nginx-1.13.6/docs/xml/change_log_conf.xml
<?xml version="1.0" ?>
<!--
  ~ Copyright [$tody.year] [Wales Yu of copyright owner]
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE configuration SYSTEM "../dtd/change_log_conf.dtd" >

<configuration>

<length>76</length>

<start>    *) </start>
<indent>       </indent>

<changes lang="ru">
    <title>Изменения в </title>
    <length>66</length>

    <bugfix>Исправление</bugfix>
    <feature>Добавление</feature>
    <change>Изменение</change>
    <security>Безопасность</security>
    <workaround>Изменение</workaround>
</changes>

<changes lang="en">
    <title>Changes with </title>
    <length>65</length>

    <bugfix>Bugfix</bugfix>
    <feature>Feature</feature>
    <change>Change</change>
    <security>Security</security>
    <workaround>Workaround</workaround>

    <month> Jan </month>
    <month> Feb </month>
    <month> Mar </month>
    <month> Apr </month>
    <month> May </month>
    <month> Jun </month>
    <month> Jul </month>
    <month> Aug </month>
    <month> Sep </month>
    <month> Oct </month>
    <month> Nov </month>
    <month> Dec </month>

</changes>

</configuration>
